### ISSUE TITLE
Superfluous title buttons

### ISSUE THREAD

**Issue by juho-jaakkola** [iionly/tidypics#23]
I find it unnecessary that when you're browsing an album, there are two buttons "Upload photos" and "Upload photos to this album".

Would you mind if I changed it so that when displaying a single album, it would have only "Upload photos" and it would add the new photos to the current album?

**Comment by iionly** [comment]
History: the old versions of Tidypics only had the "Upload photos" button (with functionality of "Upload photos to this album") displayed on the album gallery pages. I found this not good because it was difficult especially for new users to figure out how to upload photos in the first place (as they wouldn't easily see how it works) and it was also annoying for everyone else that you had to navigate to the target album page first before being able to upload photos to it.

The new "Upload photos" button is meant to be shown on all pages just to allow uploading of photos quickly with less "clicks" necessary to get to the right album page first. Now you could argue if both the "Upload photos" button and "Upload photos to this album" are necessary on album pages. But I don't think any of this buttons is superfluous even on album pages:

* only users allowed to upload images to the current album will see two buttons in the first place,
* not displaying the "Upload photos" button on album pages again results in additional navigation necessary to be able to upload photos for other users (even if they still get to see the "Upload photos button" but only the album owner gets to see only the "Upload photos to this album" only it might still result in additional navigation as even the album owner might not want to add new images specifically to the album he's currently on),
* a button with same text ("Upload photos") but different functionality depending on context (being on an album page or not) seems confusing.

One possibility might be to merge the "Upload photos to this album" functionality into the "Upload photos" lightbox when on an album page, i.e. you would get an additional option ("current album") if you are on an album page when clicking on the title button and you are allowed to add photos to this album.

**Comment by juho-jaakkola** [comment]
I guess you're right. Probably best to leave it as is.
