### ISSUE TITLE
Comments get duplicated in albums and image patches

### ISSUE THREAD

**Issue by juho-jaakkola** [iionly/tidypics#24]
If I add a comment to an image patch, the same comment gets duplicated to the album - and vice versa.

Is this by design or was it difficult to implement it so that they would have separate comments?

Consider the scenario:
 1. I create the album "My pets", and I add images of my dog to it
 2. Someone leaves the comment "Your dog is cute!" on the album
 3. Next day I upload an image of my cat
 4. Now the river item that displays a cat has the comment "Your dog is cute!" which makes no sense

**Comment by iionly** [comment]
Are you really getting the same comment twice (both on an image and on the corresponding album)? This would be a bug then.

But I think it's rather that the comment might not be added to the entity that you expect it to be added. The starting point here is the ability to comment directly on the activity page and the river entries showing comments made to the corresponding entities. In case of Tidypics: what is the expected target of a comment made on a river entry informing about new image uploads. Specifically, you can upload not only a single image but you can upload either a single image or several images at once. I tried to come up with the following:

* separate river entries for each image selected: the comments get added to the image entity and the river entry shows any comments made on this image entity.
* single river entry for every batch of images uploaded but only a single image uploaded in a batch: comments get added to this image.
* single river entry for every batch but several images uploaded: the comments get added to the corresponding album and the river entry shows the latest comments made to this album.

The latter option is likely the option you are not happy about the result (dogs vs cats). But I don't see any other / better way to handle this to be honest (apart from not displaying ANY comments on the activity page and not allowing to make comments directly from river entries. It's simply impossible to select an image as a target instead of the album in case of multiple images uploaded at once - or rather: not impossible but resulting in basically the same problem (cats vs dogs) but this time not on album level but on image level.

**Comment by iionly** [comment]
Closing for now. I think it's how it is intentionally.
