### ISSUE TITLE
batch images are not an available option in the subtype dropdown of the river/activity stream

### ISSUE THREAD

**Issue by propertunist** [iionly/tidypics#27]
the filter that appears on the river/activity page allows the selection of images or image albums. however, i only see images that were (i think) uploaded as non batches. the batches do not get listed when i chose the option for images and there is no option for image batches.

**Comment by iionly** [comment]
I still need to think about how to fix this. The filter dropdown on the activity page list the registered entity subtypes (registered for site search that is). For Tidypics the subtypes image and album are registered while the subtype tidypics_batch is not currently.

Depending on the Tidypics plugin option about what kind of river entries to be created on image uploads the subtype (of corresponding object_guid) is either tidypics_batch or image (guessing here at the moment but I think the latter case is with separate river entries for each uploaded image and I think this kind of entries you might see when filtering the activity page by images).

I think I will need to add some kind of custom search hook function(s) to fix the issue. Just registering the tidypics_batch subtype as searchable might work to some extend, too. But I don't know if there's much sense in listing the batches as search results (search and the activity page filters are directly coupled regarding relying on the registered entities). Also, registering tidypics_batch as searchable would result in an additional entry in the filter dropdown list on the activity page (qute likely confusing and selecting the image entry would still not list more). So, I think I'll have to look into the search hook functionality to see if this will be a way to fix the issue (also a single solution to work for any of the Tidypics river entries plugin option selected).

**Comment by propertunist** [comment]
yes, adding a new entry to the subtype dropwdown for the batches would just confuse users. we need the batches to be as invisible as possible to users once the files have been uploaded.
since the subtype selector on the river page only works with one single subtype, i think the best solution will be one that results in all images sharing the same subtype. this will require a database upgrade process to convert all older image batches to the standard image format.

**Comment by iionly** [comment]
Fixed (sort of...) by https://github.com/iionly/tidypics/commit/5525a47cec5aba496d67ff7f01fb3f8f82a0f83c.

Right now Elgg core takes registered entity subtypes when building the content filter dropdown. Unfortunately, this makes configuration of entries quite complicated / impossible from a 3rd party point of view. Overriding the core view wouldn't be a good solution as it would fails when two plugins try to override it to configure the filter menu entries.

For now I've registered the tidypics_batch subtype resulting in a corresponding entry to be added in the dropdown menu. I also added a plugin hook to prevent tidypics_batch related content to show up in site searches (wouldn't make sense anyway).

I've also opened an issue in the Elgg core repo (https://github.com/Elgg/Elgg/issues/9918), so we might get an improved handling of the filter menu at some time in the future.

I think it would make sense to code a plugin that allows for configuring the entries specifically, i.e. it starts with the registered subtypes by default but then allows to add/remove entries that should be used on its plugin settings page. Then it would use the custom array of types/subtypes configured instead of the registered subtypes in Elgg core (in this case the overriding the core view to build up a custom menu would work). If I have time I'll try to code it.

**Comment by propertunist** [comment]
i'm sure there must be a way to return batches AND single images together as if they are one subtype - which would be the best solution in the case of tidypics. maybe the best solution is to change resources/river.php in elgg core to support multiple subtypes? or a hook in river.php to allow for customisation of the river query before the list is rendered.
