### ISSUE TITLE
most commented images

### ISSUE THREAD

**Issue by Beaufort8** [iionly/tidypics#34]
Fatal error: Call to a member function getGUID() on null

/views/default/resources/tidypics/lists/mostcommentedimages.php
on line 40:

```
'href' => "ajax/view/photos/selectalbum/?owner_guid=" . $$logged_in_user->getGUID(),
```

delete dollar-sign:

```
'href' => "ajax/view/photos/selectalbum/?owner_guid=" . $logged_in_user->getGUID(),
```

**Comment by iionly** [comment]
Fixed by https://github.com/iionly/tidypics/commit/a17aec908ebf4eefca21ddf52981c7624cb6e7cc.

Thanks for reporting.

Next release might take a little while as I need to try some changes for the album selection popup code to work without issues also on slow connections (where it might take a while for the lightbox JS code to be loaded). This change will replace the current code for adding the "Upload photos" button anyway.
