### ISSUE TITLE
feature download all group image 

### ISSUE THREAD

**Issue by dipenpatel235** [iionly/tidypics#41]
hello..
if download all image of group then it is good feature

**Comment by iionly** [comment]
I don't think I will add such a feature (at least not in the foreseeable future due to lack of time alone). It wouldn't be simple to add such a feature: you can't just download more than a single file at once. You would have to compress them all into a single file for the download. And there could be thousands of images within a group. So, there would be server requirements to be able to compress the images, and there could be a high server load caused by compressing and not many people might want to download all images anyway. So, sorry. But I don't think such a feature will get added.
