### ISSUE TITLE
Why not show a preview

### ISSUE THREAD

**Issue by AbdulazizSobh** [iionly/tidypics#53]
Why not display the pictures while sharing the link on Facebook and other sites?
Why not show a preview of GIF files

**Comment by iionly** [comment]
That's something that has to be done on the Facebook site or whatever other site you want to link from. That's nothing within Tidypics that could define what someone adds on another site.

There were "share" plugins available for older version of Elgg that would help users with linking back from social network site to content on an Elgg site. Such a share plugin would takt care of adding the correct link code (or maybe making use of some API functions offered by Facebook etc. to define the layout with preview of such a link). I believe such a share plugin would be the approach to choose for sharing content as it could deal with all the content available on the site and not limited to the content of a single plugin only (and requiring the sharing stuff to be added in every plugin separately).

I won't offer such a sharing plugin though. I'm simply not interested in becoming a user on Facebook or other sites and if only for testing the share plugin. Maybe someone else would take the job.

I don't know what you mean with previews of GIF files. If you refer to previews on other sites it's the same matter as with the share plugin in general. If you mean "animated" gifs not being animated in the thumbnails on your Elgg site it might be because you have selected the GD image library in the Tidypics plugins settings for creating the thumbnails. The GD php extension can't resize animated gifs. So, you would have to use either the Imagick php extension or the Image Magick tools for thumbnail creation.
