### ISSUE TITLE
can't open large format of picture on 4.3.0

### ISSUE THREAD

**Issue by valmiki** [iionly/tidypics#58]
I can't open large format pictures on elgg 4.3.0. The thumbnails and small format pictures work fine.

**Comment by iionly** [comment]
Let me ask if I understand your problem correctly: it works correctly for small images but it fails to work for larger images, right?

In this case it's probably not a problem of Tidypics itself but a out-of-memory issue with the GD PHP extension used by Tidypics to create the resized image thumbnails. The memory requirement of the GD PHP extension increases with higher image resolutions.

Two ways to proceed:

- the first option is not really fixing the issue but only lessens the pain. You could increase memory_limit in Elgg's .htaccess file or the server's php.ini, e.g. from default 64M to 128M or larger (also depends on your server's amount of RAM). You could upload larger images then (but the limit due to memory would still come at higher resolutions).
- better option would be to either use the Imagick PHP extension or installing the ImageMagik tools package on your server. Both alternative image libraries have a much, much smaller memory footprint so there shouldn't be problems with larger images uploaded.

If I haven't understood your problem correctly, please explain further.

**Comment by valmiki** [comment]
It does not work for all images. Screenshot attached. I am running ELGG 4.3.0

I have installed and selected the ImageMagick executable: ImageMagick 7.1.0-45 Q16-HDRI aarch64 20319 

PHP Version | 8.1.9 |  
-- | -- | --
GD | Enabled | Elgg requires the GD extension to be loaded
imagick | Disabled |  
exec() | Enabled | Required for ImageMagick command line
Memory Available to PHP | 320MB | Change memory_limit to increase
Memory Used to Load This Page | 7.49 MB | This is approximately the minimum per page
Max File Upload Size | 109MB | Max size of an uploaded photo file
Max Post Size | 110MB | Max post size = sum of photos + html form
Max Input Time | 60s | Time script waits for upload to finish
Max Execution Time | 360s | Max time a script will run
![Schermafbeelding 2022-10-03 om 15 17 03](https://user-images.githubusercontent.com/92208/193586922-67264d9e-3c04-439f-ba10-d43ed8144817.png)

GD imagejpeg | Enabled |  
GD imagepng | Enabled |  
GD imagegif | Enabled |  
GD imagewebp | Enabled |  
EXIF | Enabled

**Comment by iionly** [comment]
Sorry, but I still can't reproduce your problem at all! Maybe you mean something different with "large format" than I did so far.

The example screenshot you posted seems to indicate that the image entry as such shows up but you have a problem with the original sized image displayed in the lightbox popup ("This image failed to load"). This would mean that the thumbnail creation worked correctly but there's some other problem.

The popup window would display the originally uploaded image file. Can you download this image file (using the "Download" menu entry in the dropdown menu not by any other means - you would need to use version 4.3.0 of Tidypics for that because the download link was indeed broken in former Tidypics versions for Elgg4)? If you can download the image this way, there's no problem with the original image file being saved on your server. In this case the problem with the same image file not showing up in the popup window might be caused by another 3rd party plugin installed on your Elgg site. Have you tested with all other 3rd party plugins (temporarily) disabled?

If you can't download the original image file either (or you checked directly in the data directory on your server and it's not there), the problem might still be a matter of setting the php variable limits too strict. Max post site sets the limit all image files uploaded in once batch together with their corresponding thumbnails are allowed to sum up to. Sorry for the "might"s and "maybe"s. But as I said everything works fine for me and all images get displayed correctly.

**Comment by valmiki** [comment]
Fixed. It turned out to be a permission issue on our side. Thanks for your help and patience.
